### ISSUE TITLE
Finalize "auto bling" script, test on a number of image sets

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/PattyGenerate#11]
We should finalize the script that "auto corrects" input images to be easier to swallow by the pipeline.

**Comment by jspaaks** [comment]
In the end, this line of thinking did not prove very useful, or at least not generally applicable. We have some image preproceesing scripts that reside [here](https://github.com/NLeSC/structure-from-motion/tree/164c84d00ca54692d8b26e46edf64ce6c437b3ef/image-preprocessing)
