### ISSUE TITLE
Create video of NLESC_SITE_1

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/PattyGenerate#19]
Videos would probably be a good source of images. We should try it out

**Comment by jspaaks** [comment]
Update: 
I recorded a video last week. I also wrote a Python script that extracts every n^{th} frame and makes a relative softlink to it in a new directory. The frames look pretty blurry, may have something to do with keyframes (which I ignored for the moment).

**Comment by jspaaks** [comment]
The frames don't have EXIF tags. I need to add these, e.g. using ``exiftool -FocalLength=2.8 img-2148.jpg``

Also, we need to add the video camera to the database of recognized cameras 
Make                            : Panasonic
Camera Model Name               : HC-X900

and look up sensor size

**Comment by nielsdrost** [comment]
The sensor seems to be 1/4.1"  (http://www.cnet.com/products/panasonic-hc-x900/specs/).

**Comment by nielsdrost** [comment]
Unfortunately the exact size of this sensor is not listed anywhere we can find.

This Wikipedia page lists quite a few sensor sizes:

http://en.wikipedia.org/wiki/Image_sensor_format#Table_of_sensor_formats_and_sizes

**Comment by jspaaks** [comment]
In the end, we added a sensor size of 3.2 mm for the Panasonic HC-X900 to the database in [RunBundler.sh](https://github.com/NLeSC/bundler_sfm/blob/711713a3be4dcff320c60aa8d529acd19bcc05bd/RunBundler.py#L304).
