### ISSUE TITLE
Create a virtual machine with the final pipeline

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/PattyGenerate#2]
We already have a virtual machine with the pipeline as of the last fastforward

**Comment by jspaaks** [comment]
Done. We describe that [here](https://github.com/NLeSC/structure-from-motion/blob/164c84d00ca54692d8b26e46edf64ce6c437b3ef/docs/install-ubuntu-14.10.md). We also made a docker. 

Closing the issue.
