### ISSUE TITLE
Do some automated testing

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/PattyGenerate#21]

**Comment by jspaaks** [comment]
I added a Python script that can help retrieve the number of points from the sparse point cloud and the dense point cloud. Could be useful as a crude quality measure in e2e testing.

https://github.com/NLeSC/PattyGenerate/blob/4f48e419418e67c3ff9b243e4b6f4e7ddce56458/number-of-points/number-of-points.py

**Comment by jspaaks** [comment]
Migrated
