### ISSUE TITLE
JSON for picture-camera position

### ISSUE THREAD

**Issue by oscarmartinezrubi** [NLeSC/PattyGenerate#23]
When you want to add information in the DB about the position/up-direction/direction from which a picture was taken please add this in a JSON file (which should have same name as image with .json)

Example: I could have a image.png which could have a image.png.json file with:

{"srid": 32633,
"x": 0.0,
"y": 0.0,
"z": 0.0,
"dx": 0.0,
"dy": 0.0,
"dz": 0.0,
"ux": 0.0,
"uy": 0.0,
"uz": 0.0,
}

**Comment by jspaaks** [comment]
added a [file](https://github.com/NLeSC/PattyGenerate/blob/7931bd67d6bad502268d3e1d669044de216fd836/parse-camera-data/readcams.py) that addresses this issue
