### ISSUE TITLE
Add masking pre-process scripts to head of pipeline

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/PattyGenerate#8]

**Comment by jspaaks** [comment]
last step convert size to 1800x1800

**Comment by jspaaks** [comment]
the stuff that proved useful is [here](https://github.com/NLeSC/structure-from-motion/tree/164c84d00ca54692d8b26e46edf64ce6c437b3ef/image-preprocessing). The last convert step to 1800x1800 was resolved differenlt, by changing the amount of memeory that is pre-allocated.
